import express from 'express';
import { getProjects, getAllProjects, getProject, createProject, updateProject, deleteProject, reorderProjects } from '../controllers/projectController.js';
import auth from '../middleware/authMiddleware.js';
import { uploadProject } from '../config/cloudinary.js';
const router = express.Router();
router.get('/', getProjects);
router.get('/all', auth, getAllProjects);
router.get('/:id', getProject);
router.post('/', auth, uploadProject.array('images', 5), createProject);
router.put('/:id', auth, uploadProject.array('images', 5), updateProject);
router.delete('/:id', auth, deleteProject);
router.patch('/reorder', auth, reorderProjects);
export default router;
